Changes the Reddit Pixel to support Oauth2
stape-io/reddit-tag pull request #1
Opened 2024-01-23 20:41 UTC by renatost

Apparently Reddit no longer supports API Key to access the conversion API. This change implements the oauth2 authentication mechanism as described in the [documentation]( https://ads-api.reddit.com/docs/v2/#section/Authentication/Reddit%20API%20Key)

2024-01-24 16:05 UTC, Bukashk0zzz requested changes
Thanks for a good work and sharing.
Please resolve issues in comments.

2024-01-24 16:05 UTC, Bukashk0zzz commented on template.tpl
> +    refreshKey().then(r => sendHttpRequest(r));
sendHttpRequest you probably mean sendRequest function here

2024-01-24 16:05 UTC, Bukashk0zzz commented on template.tpl
> +    refreshKey().then(r => sendHttpRequest(r));
sendHttpRequest you probably mean sendRequest function here

2024-01-24 16:05 UTC, Bukashk0zzz commented on template.tpl
> +    logToConsole(
please use logs standard https://github.com/stape-io/gtm-standards/blob/main/standards/GTMS-3.md

name AuthKey not allowed here

2024-01-24 16:05 UTC, Bukashk0zzz commented on template.tpl
> +        Type: 'RequestRefreshKey',
please use logs standard https://github.com/stape-io/gtm-standards/blob/main/standards/GTMS-3.md

Type here must be Request

2024-01-24 16:05 UTC, Bukashk0zzz commented on template.tpl
> +        EventName: eventType.tracking_type === 'Custom' ? eventType.custom_event_name : eventType.tracking_type,
Name RefreshKey

2024-01-24 16:05 UTC, Bukashk0zzz commented on template.tpl
> +              Type: 'ResponseRefreshKey',
please use logs standard https://github.com/stape-io/gtm-standards/blob/main/standards/GTMS-3.md

Type here must be Response

2024-01-24 16:05 UTC, Bukashk0zzz commented on template.tpl
> +              EventName: eventType.tracking_type === 'Custom' ? eventType.custom_event_name : eventType.tracking_type,
Name RefreshKey

2024-01-24 16:05 UTC, Bukashk0zzz commented on template.tpl
> +        Firestore.write('reddit/auth_key', {apiKey: body, lastUpdated: getTimestampMillis()});
Please use this standard for Firestor setting https://github.com/stape-io/gtm-standards/blob/main/standards/GTMS-6.md

2024-01-24 16:05 UTC, Bukashk0zzz commented on template.tpl
> +  return Promise.create((res, rej) => {
that's not required to use Promise here as sendHttpRequest automatically create it for you.
but you can leave it as is.

2024-01-24 19:38 UTC, renatost reviewed
glad to be able to collaborate.

2024-01-24 19:38 UTC, renatost commented on template.tpl
> +    logToConsole(
Removed AuthKey

2024-01-24 19:38 UTC, renatost commented on template.tpl
> +  return Promise.create((res, rej) => {
Using that created promise to write to firebase before returning. After I created it, realized I don't need to wait for firebase to complete.

2024-01-24 19:38 UTC, renatost commented on template.tpl
> +        EventName: eventType.tracking_type === 'Custom' ? eventType.custom_event_name : eventType.tracking_type,
I am assuming you mean Name: 'Reddit' and type 'Request' as outlined in the standards doc, correct?

2024-01-24 19:38 UTC, renatost commented on template.tpl
> +              EventName: eventType.tracking_type === 'Custom' ? eventType.custom_event_name : eventType.tracking_type,
I am assuming you mean Name: 'Reddit' and type 'Response' as outlined in the standards doc, correct?

2024-01-26 14:35 UTC, Bukashk0zzz requested changes

2024-01-26 14:35 UTC, Bukashk0zzz commented on template.tpl
> +        EventName: eventType.tracking_type === 'Custom' ? eventType.custom_event_name : eventType.tracking_type,
EventName should be RefreshKey

2024-01-26 14:35 UTC, Bukashk0zzz commented on template.tpl
> +              EventName: eventType.tracking_type === 'Custom' ? eventType.custom_event_name : eventType.tracking_type,
EventName should be RefreshKey

2024-01-26 14:35 UTC, Bukashk0zzz commented on template.tpl
> +    sendRequest(authKey.apiKey);
if result.reason == "not_found" then 
sendRequest will be used 2 times and conversion will be ended 2 times

2024-01-26 14:35 UTC, Bukashk0zzz commented on template.tpl
> +    refreshKey().then(r => sendRequest(r));
I think here should be return with data.gtmOnSuccess();

2024-01-26 14:35 UTC, Bukashk0zzz commented on template.tpl
> +}, () => refreshKey().then(r => sendRequest(r)));
I think here should be data.gtmOnFailure

2024-01-26 19:46 UTC, renatost commented on template.tpl
> +    sendRequest(authKey.apiKey);
Added a return here.

2024-01-26 19:47 UTC, renatost commented on template.tpl
> +    refreshKey().then(r => sendRequest(r));
data.gtmOnSuccess() is called inside sendRequest -- do we need to call it here again?

2024-01-26 19:47 UTC, renatost commented on template.tpl
> +}, () => refreshKey().then(r => sendRequest(r)));
data.gtmOnFailure() is called inside sendRequest -- do we need to call it here again?

2024-01-26 19:52 UTC, renatost commented on template.tpl
> +    sendRequest(authKey.apiKey);
added return here

2024-01-26 19:52 UTC, renatost commented on template.tpl
> +    refreshKey().then(r => sendRequest(r));
data.gtmOnSuccess() is called inside sendRequest -- do we need to call it here again?

2024-01-26 19:52 UTC, renatost commented on template.tpl
> +}, () => refreshKey().then(r => sendRequest(r)));
data.gtmOnFailure() is called inside sendRequest -- do we need to call it here again?

2024-01-29 09:58 UTC, Bukashk0zzz approved these changes

2024-01-29 12:41 UTC, merged